const aliases: Record<string, string[]> = {
	margin: ["margin"],
	m: ["margin"],
	marginTop: ["marginTop"],
	mt: ["marginTop"],
	marginRight: ["marginRight"],
	mr: ["marginRight"],
	marginBottom: ["marginBottom"],
	mb: ["marginBottom"],
	marginLeft: ["marginLeft"],
	ml: ["marginLeft"],
	marginX: ["marginRight", "marginLeft"],
	mx: ["marginRight", "marginLeft"],
	marginY: ["marginTop", "marginBottom"],
	my: ["marginTop", "marginBottom"],
	padding: ["padding"],
	p: ["padding"],
	paddingTop: ["paddingTop"],
	pt: ["paddingTop"],
	paddingRight: ["paddingRight"],
	pr: ["paddingRight"],
	paddingBottom: ["paddingBottom"],
	pb: ["paddingBottom"],
	paddingLeft: ["paddingLeft"],
	pl: ["paddingLeft"],
	paddingX: ["paddingRight", "paddingLeft"],
	px: ["paddingRight", "paddingLeft"],
	paddingY: ["paddingTop", "paddingBottom"],
	py: ["paddingTop", "paddingBottom"],
	bgcolor: ["backgroundColor"],
};
export default aliases;
